<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="vshulkevich" name="com.example.tests.TestContactCreation" tests="1" failures="0" timestamp="23 Nov 2015 14:02:29 GMT" time="0.114" errors="1">
  <testcase name="shouldCreateContactWithValidData" time="0.114" classname="com.example.tests.TestContactCreation">
    <error type="com.jacob.com.ComFailException" message="Can&#039;t get object clsid from progid">
      <![CDATA[com.jacob.com.ComFailException: Can't get object clsid from progid
	at com.jacob.com.Dispatch.createInstanceNative(Native Method)
	at com.jacob.com.Dispatch.<init>(Dispatch.java:99)
	at com.jacob.activeX.ActiveXComponent.<init>(ActiveXComponent.java:58)
	at autoitx4java.AutoItX.<init>(AutoItX.java:181)
	at com.example.fw.AutoItHelper.<init>(AutoItHelper.java:20)
	at com.example.fw.ApplicationManager.getAutoItHelper(ApplicationManager.java:57)
	at com.example.fw.ContactHelper.initContactCreation(ContactHelper.java:29)
	at com.example.fw.ContactHelper.createContact(ContactHelper.java:11)
	at com.example.tests.TestContactCreation.shouldCreateContactWithValidData(TestContactCreation.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
    </error>
  </testcase> <!-- shouldCreateContactWithValidData -->
</testsuite> <!-- com.example.tests.TestContactCreation -->
